### ISSUE TITLE
Settings screen cut off on mobile

### ISSUE THREAD

**Issue by schnps** [nickmilo/Cybertron#12]
On mobile, Cybertron cuts off the Settings page. Like its width isn't adaptive.

Attached examples from an Android device (2220 × 1080) in both portrait (no text shows) and landscape (some text showing). Even on an iPad the settings only display fully in landscape mode.

![Portrait - Screenshot_20210712-192257](https://user-images.githubusercontent.com/10359265/125949925-fc0a0d86-8c4f-48e5-b01f-b446795a1857.png)
![Landscape  - Screenshot_20210712-192309](https://user-images.githubusercontent.com/10359265/125949927-a5368628-b070-4c4f-b0c3-ebdb1263eb44.png)

**Comment by kjharcombe** [comment]
I have had a similar issue which I've created for iPadOS  (#13)

**Comment by urbanvietcong** [comment]
This issue should have been fixed with #11 

Or at least worked during the tests I've made before opening the pr

**Comment by schnps** [comment]
That works in my Pixel 3a (I don't have access to the iPad to test any more).

Thanks!
