### ISSUE TITLE
iPadOS Settings doesn't adjust size in Split View

### ISSUE THREAD

**Issue by kjharcombe** [nickmilo/Cybertron#13]
### Steps to reproduce

1. Open Obsidian with another app in Split View
2. Open the Obsidian settings menu
(See screenshot)
### Expected result

- The ability to view settings menu in split view without the menu being cut off. 

### Actual result

- Obsidian in split view without obscuring settings menu. 

### Environment

- Operating system: iPadOS 14.6

- Obsidian version: 1.0.3

----------

### Additional information

![IMG_DBC26BEAAF5E-1](https://user-images.githubusercontent.com/76237554/126473459-6ab9ba5d-193e-452f-9579-bc7d60451c46.jpeg)

**Comment by nickmilo** [comment]
Yes it's useful, thank you. I'm hoping to fix things in September. I have to get some help...not sure how to modify the mobile css settings effectively

**Comment by kjharcombe** [comment]
> Yes it's useful, thank you. I'm hoping to fix things in September. I have to get some help...not sure how to modify the mobile css settings effectively

I’ll give it a go. See if I’m able to fix it.

**Comment by nickmilo** [comment]
> > Yes it's useful, thank you. I'm hoping to fix things in September. I have to get some help...not sure how to modify the mobile css settings effectively
> 
> I’ll give it a go. See if I’m able to fix it.

That would be pretty awesome. I see something like California Coast's mobile theme and I'm like, "So there is a way..."

**Comment by urbanvietcong** [comment]
As in #12, this issue should have been fixed in #11. 

Sadly I can't make any test with an iPad until next week, so if you or anyone could try again using the updated code and let us know would be cool.

**Comment by kjharcombe** [comment]
@nickmilo - It appears I might have fixed this issue. See #15

**Comment by kjharcombe** [comment]
@alombi @nickmilo, I have tested this on the production version of iOS 15 and my changes still work and allows for split screen use. Hope this helps
