### ISSUE TITLE
Unable to use "card" view for notes

### ISSUE THREAD

**Issue by gsastry** [nickmilo/Cybertron#14]
I used this theme a few months ago, and I liked that it had "card" views for the notes: they appear side-by-side. When I tried it today, it looks like this:

<img width="1810" alt="Screen Shot 2021-07-28 at 22 31 34" src="https://user-images.githubusercontent.com/369096/127437054-4e10e706-9c47-4a9a-9dd1-9aa1cec07d6d.png">

Instead of like this:
<img width="1293" alt="Screen Shot 2021-07-28 at 22 33 28" src="https://user-images.githubusercontent.com/369096/127437115-0e356c4a-1014-4ff9-9259-2c96e3e73a68.png">

I can't find an option to change this. Anyone have ideas? I really dig the card view.

**Comment by nickmilo** [comment]
@gsastry Go to settings and make sure to toggle off "Sliding Panes"

**Comment by gsastry** [comment]
@nickmilo hmm, I don't have the Sliding Panes plugin installed. Are you saying to turn it OFF, or to install it and turn it on?

**Comment by nickmilo** [comment]
Install Sliding Panes and turn it on. (sorry for the non-response)

Sent via Superhuman ***@***.***>
