### ISSUE TITLE
Hiding the links in editor mode not working

### ISSUE THREAD

**Issue by stixard** [nickmilo/Cybertron#20]
Hello Nick, very cool theme thank you.
I have a problem when using with a css snipet by death.au to hide the link in edit mode
The snipet looks like this and it works fine with any other theme.

`div:not(.CodeMirror-activeline) > .CodeMirror-line .cm-string.cm-url:not(.cm-formatting) {
    font-size: 0;
}
div:not(.CodeMirror-activeline) > .CodeMirror-line .cm-string.cm-url:not(.cm-formatting)::after {
    content: '🔗';
    font-size: 1rem;
}`

Here is an example of how it works.             It does not hide the link when using Cybertron
<img src="https://user-images.githubusercontent.com/91340202/134713810-d4a8fa3a-1036-4e9a-8d47-ab6e1928320a.png" width=20% height=20%>         <img src="https://user-images.githubusercontent.com/91340202/134715112-058c3b05-5d69-435d-8760-9ec7dbc21d7b.png" width=50% height=50%>  

Thank you!

**Comment by nickmilo** [comment]
Hey, thanks to @Lithou , snippets should work now. 
I tested this one specifically, and it now works!

**Comment by nickmilo** [comment]
Just making sure that you know this is now fixed. Thanks for reporting.
