### ISSUE TITLE
Heading coloration complaint

### ISSUE THREAD

**Issue by jredwards** [nickmilo/Cybertron#31]
I really enjoy this theme, and I love it that the different headings all show in different colors. With one exception. The ### heading is the same color as the default text. The others are all different. I find myself intentionally avoiding the ### heading because it makes my notes harder to read. Just some feedback.

Thanks Nick. Enjoyed your video series as well.

**Comment by nuflowx** [comment]
Haha, I do exactly the same with avoiding ### 😅

I'm using his LYT-theme, which is the continuation of this one. Cybertron I initially liked a bit more from the colours, but figured the continuation of the theme would be more up to date version.

I haven't spent any time looking into code, but I think I'll end up changing the colour for my own theme. Must be a variable or something somewhere. I'll have a look 👀

**Comment by jredwards** [comment]
> Haha, I do exactly the same with avoiding ### 😅
> 
> I'm using his LYT-theme, which is the continuation of this one. Cybertron I initially liked a bit more from the colours, but figured the continuation of the theme would be more up to date version.
> 
> I haven't spent any time looking into code, but I think I'll end up changing the colour for my own theme. Must be a variable or something somewhere. I'll have a look 👀

I have also moved on to LYT Mode 👍
