### ISSUE TITLE
Line breaks appearing around emojis in preview mode

### ISSUE THREAD

**Issue by kalitara** [nickmilo/Cybertron#6]
When I view a note in preview mode with the Cybertron theme, line breaks are appearing before and after the emojis.
![preview mode emoji rendering](https://user-images.githubusercontent.com/13211812/115316314-f9b63400-a12d-11eb-9f67-eaf26b0a4b89.jpg)

**Comment by nickmilo** [comment]
It's the community plugin "Emoji Toolbar". Turn that off.

**Comment by nodeBody** [comment]
Then how should we go about if one wants to use emojis.

**Comment by nickmilo** [comment]
On a mac, you can summon the emoji selector window by pressing
cmd-ctrl-spacebar

**Comment by kalitara** [comment]
Got it. And, yep, removing the emoji plugin did remove the new lines. However, the emoji character ends up displaying like huge clipart and spaced farther away.

Do you think it can be fixed?

<img width="492" alt="Screen Shot 2021-04-26 at 4 12 52 PM" src="https://user-images.githubusercontent.com/13211812/116162362-773bf000-a6aa-11eb-942c-930c8c033fc8.png">

**Comment by nickmilo** [comment]
What does your "Edit Mode" text look like? There's probably something going
on there.

I can get your results if I paste: ![:stuck_out_tongue:](
https://discord.com/assets/10f25947b6687b5b103e131ca82826ab.svg)

By if I just paste this: 😛  then it looks like it should

**Comment by kalitara** [comment]
Edit mode looks normal. You can see my original screenshot for an example.

I just tried some other themes and the other themes exhibit the same issue. 

If I apply no theme, then the emoji is still displayed in the same large size but there is no extra spacing and the emoji is bottom justified with the text.

<img width="492" alt="Screen Shot 2021-04-26 at 6 03 04 PM" src="https://user-images.githubusercontent.com/13211812/116169532-b9206280-a6b9-11eb-9640-82260066f3fe.png">

**Comment by MartynKeigher** [comment]
Hey all, 

I can also confirm that this 'emjoi on next line' bug is happening to me too! I first thought it was a bug with the emoji plugin, but after testing other themes (and default \ no theme).. its only happening on Cybertron. 

In edit mode:
![image](https://user-images.githubusercontent.com/3298134/116790653-7b3d8880-aa83-11eb-8068-efe9f3639cb7.png)

In view mode:
![image](https://user-images.githubusercontent.com/3298134/116790658-8a243b00-aa83-11eb-8b7d-43dc796f2ddb.png)

Split panel:
![image](https://user-images.githubusercontent.com/3298134/116790744-ebe4a500-aa83-11eb-9052-e1a76272e3c4.png)

![image](https://user-images.githubusercontent.com/3298134/116790794-38c87b80-aa84-11eb-85e8-c56cbb109ed7.png)

**Comment by foreveryone1** [comment]
Here's a fix:

```css
img.emoji {
    display: inline-block;
}
```

**Comment by nickmilo** [comment]
Thanks BIG time @foreveryone1 . Hopefully this solves everyone's issue?

**Comment by nickmilo** [comment]
Also, I'm curious if everyone is getting the updates... This code should be at the top of the CSS if you're using the latest:

`/* MODIFIED 2021-05-02 */`

**Comment by MartynKeigher** [comment]
Hey @nickmilo , 
After updating your CSS (via Obsidian itself) ... the top of my css file does NOT have the date stamp on it.
![image](https://user-images.githubusercontent.com/3298134/116887057-d7291e00-abf7-11eb-9dac-8791d59a77cd.png)

**Comment by MartynKeigher** [comment]
OK - Just restarted Obsidian and went to obtain your theme again, and this time I do have the the date stamp at the top! Not sure what was going wrong there for me earlier and I apologize for the false alarm! 
![image](https://user-images.githubusercontent.com/3298134/116896585-663b3380-ac02-11eb-811f-dbb218e66b13.png)

**Comment by nickmilo** [comment]
@MartynKeigher Please don't apologize, that's actually exactly what I was hoping for! I noticed a few screenshots people have shared in places that didn't have some updates, so I was wondering if _any_ of the updates were getting pushed. So now I can make sure people restart Obsidian and re-obtain the theme when troubleshooting.
